// File generated by Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBAP--NTTIUD2gIx4S5xjAoalk2avGFs',
    appId: '1:427028685090:android:02d12872a1fcc3ff95857b',
    messagingSenderId: '427028685090',
    projectId: 'momentum-app-shayan',
    storageBucket: 'momentum-app-shayan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcz2bTqmscj3ci_wyAiChV1r4m9xDFAns',
    appId: '1:427028685090:ios:91c78935bbfba8b395857b',
    messagingSenderId: '427028685090',
    projectId: 'momentum-app-shayan',
    storageBucket: 'momentum-app-shayan.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );
}
